[versions]
kotlin = "2.3.0"
th2-plugin = "0.3.14"

[libraries]
th2-common-utils = { group = "com.exactpro.th2", name = "common-utils", version = "2.4.0-dev" }
th2-codec = { group = "com.exactpro.th2", name = "codec", version = "5.6.2-dev" }

rawhttp-core = { group = "com.athaydes.rawhttp", name = "rawhttp-core", version = "2.6.0" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }

auto-service = { group = "com.google.auto.service", name = "auto-service", version = "1.1.1" }

mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.2.0" }
strikt-core = { group = "io.strikt", name = "strikt-core", version = "0.34.1" }

[plugins]
th2-component = { id = "com.exactpro.th2.gradle.component", version.ref = "th2-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }